apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-project-deployment
  labels:
    app: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-project
  template:
    metadata:
      labels:
        app: my-project
    spec:
      containers:
      - name: my-project-container
        image: svignesh2409/project_ecommerce:latest
        ports:
        - containerPort: 3000
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: my-project-secrets
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: my-project-secrets
              key: CLIENT_SECRET
        - name: MONGODB
          value: "mongodb://mongo-db-service:27017/Project_Ecommerce"
        - name: SECRETKEY
          valueFrom:
            secretKeyRef:
              name: my-project-secrets
              key: SECRETKEY
