apiVersion: v1
kind: Secret
metadata:
  name: my-project-secrets
type: Opaque
data:
  CLIENT_ID: MTAzNjYzNjMwOTA2Mi1uaTV0ODFpNGN1cmV1aGxxaTc4M2YybmliczdxZm9tMS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  CLIENT_SECRET: R09DU1BYLUZURW03OTc5MW1KOGxJblZVVmhMdFNkbHFoZXk=
  SECRETKEY: c2VjcmV0

