apiVersion: v1
kind: Service
metadata:
  name: my-project-service
spec:
  selector:
    app: my-project 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000      
      targetPort: 3000 
      nodePort: 30001  

